# Generated by Django 3.0 on 2021-05-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210522_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='operate',
            field=models.CharField(choices=[('yes', 'Active'), ('no', 'Inactive')], default='yes', max_length=5),
        ),
    ]
