# Generated by Django 3.0 on 2021-06-25 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20210608_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='competence',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='formation',
        ),
        migrations.AddField(
            model_name='competence',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ccv', to='account.cv'),
        ),
        migrations.AddField(
            model_name='experience',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecv', to='account.cv'),
        ),
        migrations.AddField(
            model_name='formation',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fcv', to='account.cv'),
        ),
    ]
