# Generated by Django 3.0 on 2021-07-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20210625_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
