# Generated by Django 3.0 on 2021-07-19 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_cv_default'),
        ('jobapp', '0016_auto_20210515_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.cv'),
        ),
    ]
